### ISSUE TITLE
💾希望新增测试数据

### ISSUE THREAD

**Issue by KristenHu** [sylhuang/lanwu-miniapp#14]
希望给000001用户下新增以下数据

Tasks
- [ ] 已激活年卡一张
- [ ] 已激活次卡一张
- [ ] 未激活月卡一张

**Comment by sylhuang** [comment]
可以调已有接口操作
https://github.com/sylhuang/lanwu-miniapp/wiki/API-Reference#addcardbytype
https://github.com/sylhuang/lanwu-miniapp/wiki/API-Reference#activatecardbyid
